name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas==2.3

      - name: Run ruff for code quality
        run: |
          pip install ruff
          ruff execute.py

      - name: Convert data.xlsx to data.csv
        run: |
          # Install openpyxl if needed
          pip install openpyxl
          python -c "import pandas as pd; df = pd.read_excel('data.xlsx'); df.to_csv('data.csv', index=False)"

      - name: Execute script to generate result.json
        run: |
          python execute.py > result.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          user_name: github-actions
          user_email: github-actions@github.com

      - name: Copy result.json to public directory
        run: |
          mkdir -p public
          cp result.json public/

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add public/result.json
          git commit -m "Update result.json"
          git push